name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Check Test File Integrity
      run: |
        echo "51a501bc80c21b73d9de1e8d591d4ddefad53cd7df610093d5bcf00e9d90d2d9 HangmanGameTest.java" | sha256sum --check
      working-directory: ./src/test/java/
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Test with Gradle
      run: ./gradlew test

